---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    infoblox_servers:
      hosts:
        infoblox_grid:
          ansible_host: "{{ infoblox_provider['host'] | default('localhost') }}"